INSERT INTO TODO (TITLE, TODO_ORDER, COMPLETED) VALUES ('자바스크립트 공부하기', 1, false);
INSERT INTO TODO (TITLE, TODO_ORDER, COMPLETED) VALUES ('파이썬 공부하기', 2, false);
INSERT INTO TODO (TITLE, TODO_ORDER, COMPLETED) VALUES ('알고리즘 공부하기', 3, false);