INSERT INTO TODO (TITLE, TODO_ORDER, COMPLETED, CREATED_AT, UPDATED_AT) VALUES ('자바스크립트 공부하기', 1, false, now(), now());
INSERT INTO TODO (TITLE, TODO_ORDER, COMPLETED, CREATED_AT, UPDATED_AT) VALUES ('파이썬 공부하기', 2, false, now(), now());
INSERT INTO TODO (TITLE, TODO_ORDER, COMPLETED, CREATED_AT, UPDATED_AT) VALUES ('알고리즘 공부하기', 3, false, now(), now());